### ISSUE TITLE
Implement RPC Protocol for Message Exchange

### ISSUE THREAD

**Issue by ozgen** [cenkkg/jraft#3]
**Description:** Integrate an RPC protocol to enable communication between nodes in the Raft cluster.
**Tasks:**

- [ ] Research and choose an appropriate RPC framework/library (e.g., gRPC, Apache Thrift, Java RMI) for message exchange.
- [ ] Define the message types and their corresponding data structures using the chosen RPC framework.
- [ ] Implement the necessary RPC client and server components to handle message sending and receiving.
- [ ] Integrate the RPC protocol into the existing Raft algorithm implementation for message exchange.
- [ ] Update the message-sending logic in the Raft algorithm to utilize the RPC protocol.
- [ ] Write tests to validate the functionality and correctness of the RPC-based message exchange

.

**Comment by ozgen** [comment]
Create `com.java.jraft.rpc.client` and `com.java.jraft.rpc.server`  packages. `Junit5` should be integrated to the project and all unit test should be written. @cenkkg
