### ISSUE TITLE
Replicate Log Entries

### ISSUE THREAD

**Issue by ozgen** [cenkkg/jraft#9]
**Description:** Implement the logic for log replication from the leader to the followers.

**Tasks:**

- [ ] Add a method to the Node class for log replication.
- [ ] Determine the prefix and suffix of log entries to be sent to followers.
- [ ] Send LogRequest messages to the followers with the necessary log information.
- [ ] Write tests to ensure the correct replication of log entries.
